language: python
python:
    - 2.7
branches:
    only:
        - master
        - stable
install:
    - "pip install coverage"
    - "pip install coveralls"
    - "pip install -r requirements.txt"
script:
    - "coverage run --source=flock tests.py"
after_success:
    coveralls
